### ISSUE TITLE
Filtering with tag on class is not working

### ISSUE THREAD

**Issue by Rorick** [scalatest/scalatestplus-junit5#23]
I have some of my test classes tagged with org.scalatest.tags.Slow. Old version of runner 'co.helmethair:scalatest-junit-runner:0.1.10' properly excludes them. But newer version 'org.scalatestplus:junit-5-10_2.13:3.2.19.0' does not.

I am using Gradle and using excludeTags("org.scalatest.tags.Slow") in test task.

**Comment by Rorick** [comment]
Ok, it is working in org.scalatestplus:junit-5-10_2.13:3.2.19.1. Docs on scalatest site does not reflect the latest bugfix version. Thank you for supporting this plugin!

**Comment by Rorick** [comment]
Closing

**Comment by cheeseng** [comment]
@Rorick Sorry for the confusion, https://www.scalatest.org is updated now, fyi we also released a 3.2.19.0 build for junit 5.11.

Cheers.
